import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Sun, Sunset, Moon, Download, Info, Calendar as CalendarIcon } from 'lucide-react';
import Button from '../components/common/Button';
import RoutineCard from '../components/routine/RoutineCard';
import CalendarIntegration from '../components/calendar/CalendarIntegration';
import { useAuth } from '../hooks/useAuth';

// Enhanced routine data with afternoon routines
const morningRoutine = {
  id: 'm1',
  title: 'Daily Brightening Routine',
  time: 'morning' as const,
  steps: [
    {
      id: 'm1s1',
      productName: 'Gentle Foaming Cleanser',
      productType: 'Cleanser',
      timing: '30 seconds',
      description: 'Start your day with a gentle cleanser to remove impurities without stripping your skin.'
    },
    {
      id: 'm1s2',
      productName: 'Vitamin C Serum',
      productType: 'Treatment',
      timing: 'Wait 2 minutes',
      description: 'Apply vitamin C serum to brighten skin and protect against environmental damage.'
    },
    {
      id: 'm1s3',
      productName: 'Hydrating Gel Moisturizer',
      productType: 'Moisturizer',
      timing: 'Wait 1 minute',
      description: 'Lock in hydration with a lightweight gel moisturizer suitable for Indian climate.'
    },
    {
      id: 'm1s4',
      productName: 'Mineral Sunscreen SPF 50',
      productType: 'Sun Protection',
      timing: 'Apply generously',
      description: 'Finish with broad-spectrum sunscreen to protect from harmful UV rays.'
    }
  ]
};

const afternoonRoutine = {
  id: 'a1',
  title: 'Midday Refresh & Protection',
  time: 'afternoon' as const,
  steps: [
    {
      id: 'a1s1',
      productName: 'Antioxidant Face Mist',
      productType: 'Refresher',
      timing: 'As needed',
      description: 'Refresh and hydrate skin while providing antioxidant protection.'
    },
    {
      id: 'a1s2',
      productName: 'Sunscreen Reapplication',
      productType: 'Sun Protection',
      timing: 'Every 2-3 hours',
      description: 'Reapply sunscreen for continued protection, especially if outdoors.'
    },
    {
      id: 'a1s3',
      productName: 'Blotting Papers (if needed)',
      productType: 'Oil Control',
      timing: 'As needed',
      description: 'Gently blot excess oil without disturbing makeup or skincare.'
    }
  ]
};

const eveningRoutine = {
  id: 'e1',
  title: 'Hyperpigmentation Repair',
  time: 'evening' as const,
  steps: [
    {
      id: 'e1s1',
      productName: 'Micellar Water',
      productType: 'Makeup Remover',
      timing: '1 minute',
      description: 'Remove makeup and surface impurities gently.'
    },
    {
      id: 'e1s2',
      productName: 'Nourishing Facial Cleanser',
      productType: 'Cleanser',
      timing: '30 seconds',
      description: 'Deeply cleanse skin without disrupting its natural balance.'
    },
    {
      id: 'e1s3',
      productName: 'Alpha Arbutin + Niacinamide Serum',
      productType: 'Treatment',
      timing: 'Wait 3 minutes',
      description: 'Target hyperpigmentation and even skin tone with this powerful combination.'
    },
    {
      id: 'e1s4',
      productName: 'Peptide Moisturizer',
      productType: 'Moisturizer',
      timing: 'Final step',
      description: 'Restore and repair skin overnight with peptides and ceramides.'
    }
  ]
};

const EnhancedRoutinePage: React.FC = () => {
  const [completedSteps, setCompletedSteps] = useState<Record<string, boolean>>({});
  const [showCalendarIntegration, setShowCalendarIntegration] = useState(false);
  const { user } = useAuth();

  // Mock assessment ID - in real app, this would come from the user's latest assessment
  const mockAssessmentId = 1;

  const routines = [morningRoutine, afternoonRoutine, eveningRoutine];

  const toggleStepCompletion = (stepId: string) => {
    setCompletedSteps(prev => ({
      ...prev,
      [stepId]: !prev[stepId]
    }));
  };

  const exportRoutine = () => {
    const routineText = `
INGREVO PERSONALIZED SKINCARE ROUTINE

MORNING ROUTINE:
${morningRoutine.steps.map((step, index) => 
  `${index + 1}. ${step.productName} (${step.productType})
     Timing: ${step.timing}
     ${step.description}`
).join('\n\n')}

AFTERNOON ROUTINE:
${afternoonRoutine.steps.map((step, index) => 
  `${index + 1}. ${step.productName} (${step.productType})
     Timing: ${step.timing}
     ${step.description}`
).join('\n\n')}

EVENING ROUTINE:
${eveningRoutine.steps.map((step, index) => 
  `${index + 1}. ${step.productName} (${step.productType})
     Timing: ${step.timing}
     ${step.description}`
).join('\n\n')}

Generated by Ingrevo - Your AI Skincare Assistant
Visit: https://ingrevoskin.netlify.app
    `;
    
    const blob = new Blob([routineText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ingrevo-skincare-routine.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const renderInteractiveRoutine = (routine: any, timeIcon: React.ReactNode) => {
    return (
      <motion.div 
        className="card"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center">
            {timeIcon}
            <div className="ml-3">
              <h3 className="text-xl font-semibold">{routine.title}</h3>
              <p className="text-sm text-neutral-500 capitalize">{routine.time} Routine</p>
            </div>
          </div>
          <div className="text-sm text-neutral-500">
            {routine.steps.filter((step: any) => completedSteps[step.id]).length}/{routine.steps.length} completed
          </div>
        </div>

        <div className="space-y-4">
          {routine.steps.map((step: any, index: number) => (
            <motion.div 
              key={step.id}
              className={`p-4 rounded-lg border-2 transition-all cursor-pointer ${
                completedSteps[step.id] 
                  ? 'border-success-200 bg-success-50' 
                  : 'border-neutral-200 hover:border-primary-200'
              }`}
              onClick={() => toggleStepCompletion(step.id)}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="flex items-start">
                <div className={`flex-shrink-0 w-6 h-6 rounded-full border-2 flex items-center justify-center mr-4 mt-1 transition-all ${
                  completedSteps[step.id]
                    ? 'border-success-500 bg-success-500'
                    : 'border-neutral-300 hover:border-primary-500'
                }`}>
                  {completedSteps[step.id] && (
                    <motion.svg
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      width="14" 
                      height="14" 
                      viewBox="0 0 14 14" 
                      fill="none"
                    >
                      <path 
                        d="M11 4L5.5 9.5L3 7" 
                        stroke="white" 
                        strokeWidth="2" 
                        strokeLinecap="round" 
                        strokeLinejoin="round"
                      />
                    </motion.svg>
                  )}
                </div>
                
                <div className="flex-grow">
                  <div className="flex items-center justify-between mb-2">
                    <h4 className={`font-semibold ${completedSteps[step.id] ? 'line-through text-neutral-500' : ''}`}>
                      {step.productName}
                    </h4>
                    <div className="flex items-center text-sm text-neutral-500">
                      <span className="mr-1">⏱️</span>
                      {step.timing}
                    </div>
                  </div>
                  
                  <p className="text-sm text-neutral-600 mb-2">{step.productType}</p>
                  <p className={`text-sm ${completedSteps[step.id] ? 'text-neutral-400' : 'text-neutral-600'}`}>
                    {step.description}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    );
  };

  return (
    <div className="min-h-screen bg-neutral-50 pt-24 pb-16">
      <div className="container mx-auto px-4 md:px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div 
            className="text-center mb-10"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="text-3xl md:text-4xl font-bold mb-4">Smart Skincare Routines</h1>
            <p className="text-neutral-600 mb-6">
              Interactive routines customized for your skin profile with timing guidance and progress tracking.
            </p>
            
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Button
                variant="outline"
                onClick={exportRoutine}
                icon={<Download size={18} />}
                iconPosition="left"
              >
                Export Routine
              </Button>
              {user && (
                <Button
                  variant="primary"
                  onClick={() => setShowCalendarIntegration(!showCalendarIntegration)}
                  icon={<CalendarIcon size={18} />}
                  iconPosition="left"
                >
                  {showCalendarIntegration ? 'Hide' : 'Add to'} Google Calendar
                </Button>
              )}
            </div>
          </motion.div>

          {/* Google Calendar Integration - Only show if user is authenticated */}
          {showCalendarIntegration && user && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="mb-10"
            >
              <CalendarIntegration
                routines={routines}
                assessmentId={mockAssessmentId}
                userId={user.id}
              />
            </motion.div>
          )}

          <motion.div 
            className="bg-primary-50 rounded-xl p-6 mb-10 border border-primary-100"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <div className="flex items-start">
              <div className="h-10 w-10 rounded-full bg-primary-100 flex items-center justify-center mr-4 flex-shrink-0">
                <Info size={20} className="text-primary-600" />
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-1">Smart Routine Features</h3>
                <p className="text-neutral-600 mb-2">
                  These interactive routines adapt to your lifestyle and skin needs:
                </p>
                <ul className="list-disc list-inside space-y-1 text-neutral-600 text-sm">
                  <li>✅ Check off steps as you complete them to track progress</li>
                  <li>⏰ Follow timing recommendations for optimal absorption</li>
                  <li>📅 Add routines to Google Calendar with automatic reminders</li>
                  <li>🌤️ Afternoon routine adjusts based on your work environment</li>
                  <li>📄 Export your routine to share with dermatologists</li>
                </ul>
              </div>
            </div>
          </motion.div>

          {/* Interactive Routines */}
          <div className="grid lg:grid-cols-2 gap-8 mb-12">
            {/* Morning Routine */}
            <div>
              <motion.div 
                className="flex items-center mb-4"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.3 }}
              >
                <Sun size={24} className="text-warning-500 mr-2" />
                <h2 className="text-xl font-bold">Morning Routine</h2>
              </motion.div>
              {renderInteractiveRoutine(morningRoutine, 
                <div className="h-12 w-12 rounded-full bg-warning-100 flex items-center justify-center">
                  <Sun size={24} className="text-warning-600" />
                </div>
              )}
            </div>

            {/* Afternoon Routine */}
            <div>
              <motion.div 
                className="flex items-center mb-4"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.4 }}
              >
                <Sunset size={24} className="text-accent-500 mr-2" />
                <h2 className="text-xl font-bold">Afternoon Refresh</h2>
              </motion.div>
              {renderInteractiveRoutine(afternoonRoutine,
                <div className="h-12 w-12 rounded-full bg-accent-100 flex items-center justify-center">
                  <Sunset size={24} className="text-accent-600" />
                </div>
              )}
            </div>
          </div>

          {/* Evening Routine - Full Width */}
          <div className="mb-12">
            <motion.div 
              className="flex items-center mb-4"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
            >
              <Moon size={24} className="text-primary-500 mr-2" />
              <h2 className="text-xl font-bold">Evening Routine</h2>
            </motion.div>
            <div className="max-w-4xl mx-auto">
              {renderInteractiveRoutine(eveningRoutine,
                <div className="h-12 w-12 rounded-full bg-primary-100 flex items-center justify-center">
                  <Moon size={24} className="text-primary-600" />
                </div>
              )}
            </div>
          </div>

          {/* Routine Builder CTA */}
          <motion.div 
            className="mt-16 bg-gradient-to-r from-primary-500 to-accent-500 rounded-2xl p-8 text-white text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
          >
            <h2 className="text-2xl font-bold mb-4">Ready to Get Started?</h2>
            <p className="text-lg mb-6 opacity-90">
              Take our comprehensive skin assessment to get personalized routines and Google Calendar integration
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Button
                variant="outline"
                className="border-white text-white hover:bg-white/10"
                onClick={() => window.location.href = '/assessment'}
              >
                Take Skin Assessment
              </Button>
              <Button
                variant="outline"
                className="border-white text-white hover:bg-white/10"
                onClick={() => window.location.href = '/ingredients'}
              >
                Explore Ingredients Database
              </Button>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default EnhancedRoutinePage;